### PR TITLE
General improvements

### PR DESCRIPTION
**Pull request by Domi04151309**
### Changes:
- Add content description to ImageViews for better accessibility
- Unified padding and margin on activities with resource values
- Toolbars with back buttons in SettingsActivity and AboutActivity for better user flow
- Vector graphics instead of bitmaps for some icons
- Fix notification bug with some devices that invert notifications on dark mode which causes a black notification background that doesn't match the default dark gray one.
- Improves Android 10 dark mode support for notification

### CODE REVIEW

**Comment by adolfintel** [comment]
Wow, lots of improvements. I'll test this in the next few days and merge it.
Thank you!

**Comment by Domi04151309** [comment]
The notification bug could also be the reason for Issue #33

**Comment by adolfintel** [comment]
This PR will be merged in the next release (1.4)

**Comment by Domi04151309** [comment]
When will this be merged?

**Comment by adolfintel** [comment]
@Domi04151309 In a few days. I'm currently working on an update for LibreSpeed, as soon as it's done I'll update OpenPods as well

**Comment by Domi04151309** [comment]
It has been a few days now but it's understandable that it's not merged yet because it are strange times.

**Comment by adolfintel** [comment]
I know, I had planned to merge it one of these days but there has been a lot of delays. I live in Lombardy, in Italy, I'm literally scared that I'll run out of food, I'm too anxious to work on this, or any of my other projects.

**Comment by rafsanjani** [comment]
I got one issue with this branch. In Light mode, the percentage texts are not visible. They are visible in Dark mode however.

Samsung Galaxy Note 9
Android 10

**Comment by adolfintel** [comment]
Merged with #65

**Pull request closed without merging**
