### PR TITLE
Add special values for Android > 9

### PR DESCRIPTION
**Pull request by Domi04151309**
Related to #76 
Works as intended on Android 10. Not tested on lower versions.

### CODE REVIEW

**Comment by adolfintel** [comment]
Awesome. I'll test it on Android 9 and see if it works properly

**Comment by adolfintel** [comment]
That seems to work just fine. Thanks!

**Comment by Electric1447** [comment]
Are you sure it properly works on Oreo and older?

**Comment by adolfintel** [comment]
It displays correctly on my phone with Android 9, I don't have anything older to test it though.

**Comment by Electric1447** [comment]
I do have my old S8 for testing, would report back if any issues occur

**Comment by Domi04151309** [comment]
I'm pretty sure that won't make a difference. It's more like a division between > 9 and ≤ 9.

**Comment by Electric1447** [comment]
Android 8 handles dark theme differently than 9 and 10. So dark theme is really dependent on the Android version and rom.

**Comment by Domi04151309** [comment]
Yes but the pull request doesn't change any values for versions below 9. So if it worked before it should still work.

**Comment by Electric1447** [comment]
I did not notice this, you are correct.

**Pull request merged**
